services:
  app:
    build: .
    ports:
      - "9292:9292"
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - ./log:/app/log
    depends_on:
      - redis
    networks:
      - app-network
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge